sudo: required
dist: trusty

services:
  - docker

script:
  - ./ci/run.sh check openctf

before_deploy:
  - ./ci/run.sh build openctf ${TRAVIS_TAG}-${TRAVIS_OS_NAME}

notifications:
  email: false

deploy:
  - provider: releases
    api_key: $AUTH_TOKEN
    file:
      - "openctf-*"
    on:
      tags: true
    skip_cleanup: true
