language: rust
cache: cargo
dist: trusty
sudo: false

env:
  global:
    - PROJECT_NAME=openctf

matrix:
  include:
    - os: linux
      rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu
  fast_finish: true

before_script: rustup target add $TARGET || echo ok
script:
  - if [ -z "$TRAVIS_TAG" ]; then cargo check --all --target $TARGET; fi

before_deploy: ./ci/package $TRAVIS_TAG $TARGET

deploy:
  - provider: releases
    api_key: $AUTH_TOKEN
    skip_cleanup: true
    file_glob: true
    file:
      - "openctf-*"
    on:
      tags: true
  - provider: script
    script: ./ci/book
    skip_cleanup: true
    on:
      tags: true

notifications:
  email: false
