sudo: required
dist: trusty

services:
  - docker

script:
  - if [ -z "$TRAVIS_TAG" ]; then ./ci/run.sh check openctf; fi

before_deploy:
  - ./ci/run.sh build openctf ${TRAVIS_TAG}-${TRAVIS_OS_NAME}

notifications:
  email: false

deploy:
  - provider: releases
    api_key: $AUTH_TOKEN
    skip_cleanup: true
    file_glob: true
    file:
      - "openctf-*"
    on:
      tags: true
  - provider: script
    script: ./ci/book.sh
    skip_cleanup: true
    on:
      tags: true