[package]
name = "openctf"
version = "0.1.0"
authors = ["Michael <localhost>"]

[workspace]
members = [".", "cache", "cli", "config"]

[dependencies]
cache = { path = "cache" }
config = { path = "config" }
embed = { git = "https://github.com/iptq/embed" }

failure = "0.1.1"
rocket = "0.3"
