[package]
name = "openctf"
version = "0.0.0-8"
authors = ["Michael <localhost>"]
build = "src/build.rs"

[workspace]
members = [".", "components/cache", "components/task_queue"]

[dependencies]
base64 = "0.9"
bcrypt = "0.2"
cache = { path = "components/cache" }
diesel = { version = "1.3", features = ["mysql"] }
embed = { git = "https://github.com/iptq/embed" }
env_logger = "0.5"
failure = "0.1.1"
idna = "0.1"
lazy_static = "1.0"
log = "0.4"
mime_guess = "2.0.0-alpha.6"
r2d2 = "0.8"
r2d2-diesel = "1.0"
regex = "1.0"
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = { version = "0.3", default-features = false }
serde = "1.0"
serde_cbor = "0.9"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.2"
task_queue = { path = "components/task_queue" }
toml = "^0.4.7"
walkdir = "2.2"
