[package]
name = "openctf"
version = "0.0.0-2"
authors = ["Michael <localhost>"]

[workspace]
members = [".", "cache"]

[dependencies]
cache = { path = "cache" }
embed = { git = "https://github.com/iptq/embed" }

bcrypt = "0.2"
env_logger = "0.5"
failure = "0.1.1"
lazy_static = "1.0"
mime_guess = "2.0.0-alpha.6"
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = { version = "0.3", default-features = false }
serde = "1.0"
structopt = "0.2"
tera = "0.11"

r2d2 = "0.8"
r2d2-diesel = "1.0"
diesel = { version = "1.3", features = ["mysql"] }
