[package]
name = "librectf"
version = "0.1.0"
authors = ["Michael Zhang <failed.down@gmail.com>"]

[workspace]
members = [
    "components/admin",
    "components/api",
    "components/cache",
    "components/core",
    "components/filestore",
    "components/jail",
    "components/worker",
]

[dependencies]
actix-web = "0.7"
config = "0.9"
env_logger = "0.5"
serde = "1.0"
serde_derive = "1.0"
structopt = "0.2"

admin = { path = "components/admin" }
api = { path = "components/api" }
core = { path = "components/core" }
