[package]
name = "openctf"
version = "0.1.0"
authors = ["Michael <localhost>"]

[[bin]]
name = "openctf"
path = "cli/main.rs"

[dependencies]
actix = "0.7.0"
actix-web = "0.6.15"
cfg-if = "0.1.4"
either = "1.5.0"
env_logger = "0.5.10"
failure = "0.1.1"
regex = "1.0.1"
rust-embed = "3.0.0"
structopt = "0.2.10"
tera = "0.11.8"
walkdir = "2.1.4"
