[package]
name = "openctf"
version = "0.0.0-1"
authors = ["Michael <localhost>"]

[workspace]
members = [".", "bin", "cache", "cfgmacro", "cfgmacro/cfgmacro-derive", "orm", "orm/orm-derive"]

[dependencies]
cache = { path = "cache" }
cfgmacro = { path = "cfgmacro" }
embed = { git = "https://github.com/iptq/embed" }

failure = "0.1.1"
lazy_static = "1.0"
mime_guess = "2.0.0-alpha.6"
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = { version = "0.3", default-features = false }
serde = "1.0"
tera = "0.11"
