[admin]
database_url = "mysql://root:password@localhost:3306/openctf"

[api]
database_url = "mysql://root:password@localhost:3306/openctf"
bind_host = "127.0.0.1"
bind_port = 8000
secret_key = "secret"

[filestore]
url_prefix = "http://localhost/filestore"
bind_host = "127.0.0.1"
bind_port = 6201
push_password = "push"
pull_password = "pull"
storage_dir = "data"
