[package]
name = "cfgmacro"
version = "0.1.0"
authors = ["Michael Zhang <failed.down@gmail.com>"]

[lib]
path = "lib.rs"

[dependencies]
cfgmacro-derive = { path = "derive" }
clap = "2.32"
toml = "0.4"
