[package]
name = "filestore"
version = "0.1.0"
authors = ["Michael Zhang <failed.down@gmail.com>"]

[features]
default = ["server"]
server = []

[dependencies]
env_logger = "0.5"
hyper = "0.12"
log = "0.4"
structopt = "0.2"
