[package]
name = "cli"
version = "0.1.0"
authors = ["Michael <localhost>"]

[[bin]]
name = "openctf"
path = "bin/cli.rs"

[dependencies]
failure = "0.1.1"
openctf = { path = "../openctf" }
structopt = "0.2.10"
