[package]
name = "cli"
version = "0.1.0"
authors = ["Michael <localhost>"]

[[bin]]
name = "openctf"
path = "main.rs"

[dependencies]
failure = "0.1.1"
env_logger = "0.5"
openctf = { path = ".." }
structopt = "0.2.10"
