[package]
name = "worker"
version = "0.1.0"
authors = ["Michael Zhang <failed.down@gmail.com>"]

[dependencies]
core = { path = "../../components/core" }
shiplift = { version = "0.3", git = "https://github.com/softprops/shiplift.git" }
structopt = "0.2"
